
/* task-1 */
export const UPDATE_COUNTRY_LIST = 'UPDATE_COUNTRY_LIST';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';

/* task-2 */
export const UPDATE_COUNTER = 'UPDATE_COUNTER';

/* task-4 */
export const ADD_GUESS_INFO = 'ADD_GUESS_INFO'
export const ADD_SELECTED_NUMBER = 'ADD_SELECTED_NUMBER'

/* task-5 */
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_MOST_USED_CURRENCY_LIST = 'GET_MOST_USED_CURRENCY_LIST';

